CREATE DATABASE `ecg`

USE `ecg`

CREATE TABLE postures (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE positions (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE researchers (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE subjects (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Firstname VARCHAR(50) NOT NULL,
  Lastname VARCHAR(50) NOT NULL,
  Sex BOOL NOT NULL,
  Age INTEGER UNSIGNED NOT NULL,
  Height INTEGER UNSIGNED NOT NULL,
  Weight INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE states (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE places (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE algRpeaks (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE algPreproc (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE algFeatures (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE diseases (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
)

CREATE TABLE sessions (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  places_ID INTEGER UNSIGNED NOT NULL,
  Stamp DATETIME NOT NULL,
  Temperatur DOUBLE NOT NULL,
  Humidity DOUBLE NOT NULL,
  Note LONGTEXT NULL,
  PRIMARY KEY(ID),
  INDEX Sessions_FKIndex1(places_ID)
)

CREATE TABLE SubDiseases (
  subjects_ID INTEGER UNSIGNED NOT NULL,
  diseases_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(subjects_ID, diseases_ID),
  INDEX Subjects_has_Diseases_FKIndex1(subjects_ID),
  INDEX Subjects_has_Diseases_FKIndex2(diseases_ID)
)

CREATE TABLE SessionResearchers (
  sessions_ID INTEGER UNSIGNED NOT NULL,
  researchers_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(sessions_ID, researchers_ID),
  INDEX Sessions_has_Researchers_FKIndex1(sessions_ID),
  INDEX Sessions_has_Researchers_FKIndex2(researchers_ID)
)

CREATE TABLE ecgData (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  sessions_ID INTEGER UNSIGNED NOT NULL,
  subjects_ID INTEGER UNSIGNED NOT NULL,
  positions_ID INTEGER UNSIGNED NOT NULL,
  states_ID INTEGER UNSIGNED NOT NULL,
  postures_ID INTEGER UNSIGNED NOT NULL,
  BPSys INTEGER UNSIGNED NOT NULL,
  BPDia INTEGER UNSIGNED NOT NULL,
  Puls INTEGER UNSIGNED NOT NULL,
  ECG LONGTEXT NOT NULL,
  Note LONGTEXT NULL,
  PRIMARY KEY(ID),
  INDEX ECGData_FKIndex2(postures_ID),
  INDEX ECGData_FKIndex3(states_ID),
  INDEX ECGData_FKIndex4(positions_ID),
  INDEX ECGData_FKIndex5(subjects_ID),
  INDEX ECGData_FKIndex6(sessions_ID)
)

CREATE TABLE templates (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  algPreproc_ID INTEGER UNSIGNED NOT NULL,
  algFeatures_ID INTEGER UNSIGNED NOT NULL,
  algRpeaks_ID INTEGER UNSIGNED NOT NULL,
  ecgData_ID INTEGER UNSIGNED NOT NULL,
  template LONGTEXT NOT NULL,
  PRIMARY KEY(ID),
  INDEX Erkennungswerte_FKIndex2(ecgData_ID),
  INDEX Erkennungswerte_FKIndex3(algRpeaks_ID),
  INDEX Erkennungswerte_FKIndex4(algFeatures_ID),
  INDEX templates_FKIndex4(algPreproc_ID)
)

